import numpy as np

def readVTKB(fname):
    """ Read 3D image into numpy with unsigned char

    # This is basically used for input data of image skeleton tools Alexandru C. Telea, http://www.staff.science.uu.nl/~telea001/
    # https://github.com/Forceflow/cuda_voxelizer, https://www.patrickmin.com/binvox/
    
    *.vtk format
    ---------
    # vtk DataFile Version 3.0
    #generated by IMA3D
    BINARY
    DATASET STRUCTURED_POINTS
    DIMENSIONS 31 31 31
    ORIGIN 0 0 0
    SPACING 1 1 1
    CELL_DATA 27000
    SCALARS voxel_data unsigned_char
    LOOKUP_TABLE default
    [binary raw image data.....]

    Author:Bin Wang(binwang.0213@gmail.com)
    Date: Jan. 2020
    """
    img=None
    with open(fname, mode='rb') as file: # b is important -> binary
        for li,line in enumerate(file):
            #Head
            if(li==4): 
                NXYZ=np.array([int(t) for t in line.decode('ascii').split()[1:4]])-1
                NumVoxels=NXYZ[0]*NXYZ[1]*NXYZ[2]
                print("Image Size=",NXYZ,NumVoxels)
            #Raw data
            if(li==10):
                img=np.frombuffer(line,dtype=np.uint8)
                assert len(img)==NXYZ[0]*NXYZ[1]*NXYZ[2], "Wrong Data size %d->%d" % (len(img),NumVoxels)
                print("Image value range=",[np.min(img),np.max(img)])
    
    if(img is not None):
        img_3D=np.array(np.reshape(img,NXYZ,order='F'),dtype=np.uint8)
        return img_3D

def Image2VTKB(fname,img):
    """ Convert 3D image into binary vtk with unsigned char

    # This is basically used for input data of image skeleton tools Alexandru C. Telea, http://www.staff.science.uu.nl/~telea001/
    # https://github.com/Forceflow/cuda_voxelizer, https://www.patrickmin.com/binvox/
    
    *.vtk format
    ---------
    # vtk DataFile Version 3.0
    #generated by [binvox], http://www.google.com/search?q=binvox
    BINARY
    DATASET STRUCTURED_POINTS
    DIMENSIONS 400 400 400
    ORIGIN 0 0 0
    SPACING 1 1 1
    POINT_DATA 64000000
    SCALARS voxel_data unsigned_char
    LOOKUP_TABLE default
    [binary raw image data.....]

    Author:Bin Wang(binwang.0213@gmail.com)
    Date: Jan. 2020
    """
    header=b""
    header+=b"# vtk DataFile Version 3.0\n"
    header+=b"#Generated by PyGeoMesh\n"
    header+=b"BINARY\n"
    header+=b"DATASET STRUCTURED_POINTS\n"
    header+=b"DIMENSIONS %d %d %d\n" % (img.shape[0],img.shape[1],img.shape[2])
    header+=b"ORIGIN 0 0 0\n" 
    header+=b"SPACING 1 1 1\n" 
    header+=b"POINT_DATA %d\n" %(img.shape[0]*img.shape[1]*img.shape[2]) 
    header+=b"SCALARS voxel_data unsigned_char\n"
    header+=b"LOOKUP_TABLE default\n"
    with open(fname,'wb') as f:
        f.write(header)
        f.write(img.flatten(order="F").tobytes())